### PR TITLE
Lock Down Org Features CU-tq5m45

### PR DESCRIPTION
**Pull request by mahamzayed**
# Description

The purpose of this PR is to restrict access to certain parts of the platform for users who first sign up and are set to the default sandbox organization. Users would need to create an account in order to get access to the following features:

- People Page
- Teams Page
- Publishing Page
- Settings Page
- Within a dataset, the ability to add permissions if you have access
- Within a dataset, the ability to access the publishing tab

All but the last two will redirect to a create organization page. The button is not active yet, as I'm working on the create organization modal in another branch.

This is being pushed to a feature branch for now so as not to mess with the current functionality in dev while the backend is being worked on.

## Clickup Ticket

[CU-tq5m45](https://app.clickup.com/t/CU-tq5m45)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

1. Navigate to the app and login as usual. An `isSandboxOrg` flag has been added to Vuex and set to true for testing purposes.
2. Try navigating to all the pages listed above. You should be redirected to the restricted access page.
3. Navigate to a dataset in which you have access to. You should not be able to view the Publishing tab in settings or add permissions to users.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added unit tests that prove my fix is effective or that my feature works
- [ ] I have pushed the final commit message using the [changelog format](https://github.com/Pennsieve/pennsieve-app/wiki/CHANGELOG)

### CODE REVIEW

**Comment by mahamzayed** [comment]
@cameronbaney I'm aware that there's a console error that appears when clicking on the `Publishing` navigation page. I will address in a separate PR.

**Review by cameronbaney — APPROVED** [review]
This looks great. My only nit feedback is to move the logic about the redirect for sandbox orgs into main.js. My thoughts here is this would allow for a centralized location of what routes are blocked and require a redirect, rather than having the check in each specific route

**Comment by cameronbaney** [comment]
Will the sandbox flag be a feature flag? If so, that can be mocked and the code can be changed into where it really needs to be.

**Comment by mahamzayed** [comment]
> Will the sandbox flag be a feature flag? If so, that can be mocked and the code can be changed into where it really needs to be.

@cameronbaney Yes it will be a feature flag that will be returned from the organization endpoint that's being created. I wanted to mock the code to do just that but didn't really see any logic in vuex to modify the features in an org. If you can point me in the right direction that would be great!

**Comment by cameronbaney** [comment]
If it's a new endpoint that's being created, it sounds like it will be different data than our current feature flag system. The way you're mocking it is good for now then. 

Not useful now, but wanted to explain how you could update feature flags in Vuex to mock this. The feature flags are on the organization object, so you can use the `updateActiveOrganization` action. In vue devtools, this would add a `NEW_FLAG` feature flag:

```
$vm0.$store.dispatch('updateActiveOrganization',  {
  ...$vm0.$store.state.activeOrganization,
  organization: {
    ...$vm0.$store.state.activeOrganization.organization,
    features: [...$vm0.$store.state.activeOrganization.organization.features, 'NEW_FLAG']
  }
})
```

**Comment by mahamzayed** [comment]
> If it's a new endpoint that's being created, it sounds like it will be different data than our current feature flag system. The way you're mocking it is good for now then.
> 
> Not useful now, but wanted to explain how you could update feature flags in Vuex to mock this. The feature flags are on the organization object, so you can use the `updateActiveOrganization` action. In vue devtools, this would add a `NEW_FLAG` feature flag:
> 
> ```
> $vm0.$store.dispatch('updateActiveOrganization',  {
>   ...$vm0.$store.state.activeOrganization,
>   organization: {
>     ...$vm0.$store.state.activeOrganization.organization,
>     features: [...$vm0.$store.state.activeOrganization.organization.features, 'NEW_FLAG']
>   }
> })
> ```

@cameronbaney Thanks for this! So I spoke with Anand and I misspoke, I don't think a new endpoint is being created, just that the feature flag is going to be updated with the sandbox param:

```
so we're using feature flags to identify it as a sandbox org... I'm not sure how that works on the frontend, but as long as you can identify the org by ID and check if it has a feature called "SandboxOrgFeature" (or perhaps sandbox_org_feature) that would be the best way to identify it

it's name and slug will also be "__sandbox__
```

**Comment by mahamzayed** [comment]
Regardless, I'll keep what I have for now and just adjust once the endpoint is put in place just to have it in the feature branch.

**Pull request merged**
