### PR TITLE
Add scaffolding for Github releases dataset type in pennsieve

### PR DESCRIPTION
**Pull request by vijaysparc**
- created routes, and components for GitHub Releases dataset type
- some changes were coming from 'main' branch
- the content on these pages is placeholder, will update once the remaining components are developed

New UI with Releases tab in primary nav
github-releases-dataset-type

### CODE REVIEW

**Review by annaleeswitek — APPROVED** [review]
This looks good so far! Nice!

**Review by annaleeswitek — CHANGES_REQUESTED** [review]
Checks are failing for this - here is the error. We should look into why this is being thrown before merging 
Screenshot 2024-08-06 at 12 15 52 PM

**Comment by vijaysparc** [comment]
removed the code that was causing build issues. Added it initially to be consistent with navigation guards like in other pages. However, the route the navigation guard was trying to conditionally navigate to is non-existent (route name: 'create-org'). Let me know if this guard was intended for any other reasons, or what is the page the guard is intended to direct it to.

**Review by annaleeswitek — APPROVED** [review]

**Comment by annaleeswitek** [comment]
> removed the code that was causing build issues. Added it initially to be consistent with navigation guards like in other pages. However, the route the navigation guard was trying to conditionally navigate to is non-existent (route name: 'create-org'). Let me know if this guard was intended for any other reasons, or what is the page the guard is intended to direct it to.

Ok thank you! I merged your code to dev. WIll investigate the issue with Create Org.

**Pull request merged**
